// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBa75WpNjd2Eq8F__FB_cgtwH4-SqM-jM',
    appId: '1:523905444613:web:54341d617715a46557a56c',
    messagingSenderId: '523905444613',
    projectId: 'flora-7b733',
    authDomain: 'flora-7b733.firebaseapp.com',
    databaseURL: 'https://flora-7b733-default-rtdb.firebaseio.com',
    storageBucket: 'flora-7b733.appspot.com',
    measurementId: 'G-09VF066QHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG-yaf2XEPUxRXdTvXnwVF_-Pz6Qz5wRw',
    appId: '1:523905444613:android:b7d7efdc500b58ad57a56c',
    messagingSenderId: '523905444613',
    projectId: 'flora-7b733',
    databaseURL: 'https://flora-7b733-default-rtdb.firebaseio.com',
    storageBucket: 'flora-7b733.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNP-aSZ5Gw5I4kSkWMMUKvD9-wlF2VXCU',
    appId: '1:523905444613:ios:17eae4731aa52a4957a56c',
    messagingSenderId: '523905444613',
    projectId: 'flora-7b733',
    databaseURL: 'https://flora-7b733-default-rtdb.firebaseio.com',
    storageBucket: 'flora-7b733.appspot.com',
    iosBundleId: 'com.example.flora',
  );
}
